// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU-QeGwNbVtUksuufXuMI4a349s_j44EQ',
    appId: '1:895365121984:web:32d72d5ab2bd4f1388ea25',
    messagingSenderId: '895365121984',
    projectId: 'prod-shopq',
    authDomain: 'prod-shopq.firebaseapp.com',
    storageBucket: 'prod-shopq.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpu2Wt6kswjNG3pDnjXKrAEg569GGxzkE',
    appId: '1:411644656998:android:2faa7201daf7f4194d9ca7',
    messagingSenderId: '411644656998',
    projectId: 'shopq-multi-vendor',
    storageBucket: 'shopq-multi-vendor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8HmIWNisWr_LT2Cl4PW1lEodjc2rx2Cw',
    appId: '1:411644656998:ios:ba3fe07ad41310c24d9ca7',
    messagingSenderId: '411644656998',
    projectId: 'shopq-multi-vendor',
    storageBucket: 'shopq-multi-vendor.firebasestorage.app',
    iosBundleId: 'com.aradhyatech.shopq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdBvD0IADEpm51iw7FPgYv1hjhAPvUxo0',
    appId: '1:895365121984:ios:2cd08512a47f4fa188ea25',
    messagingSenderId: '895365121984',
    projectId: 'prod-shopq',
    storageBucket: 'prod-shopq.firebasestorage.app',
    iosBundleId: 'com.aradhyatech.shopq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU-QeGwNbVtUksuufXuMI4a349s_j44EQ',
    appId: '1:895365121984:web:d38ad659096d281a88ea25',
    messagingSenderId: '895365121984',
    projectId: 'prod-shopq',
    authDomain: 'prod-shopq.firebaseapp.com',
    storageBucket: 'prod-shopq.firebasestorage.app',
  );
}
